version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rails:
    build: .
    volumes:
      - .:/myapp
      - bundle-data:/usr/local/bundle
    environment:
      - RAILS_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=myapp_production
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - rails
    networks:
      - app-network

  tests:
    build: .
    environment:
      RAILS_ENV: test
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: myapp_test
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "bundle exec rails db:test:prepare && bundle exec rspec"

volumes:
  bundle-data:
  postgres-data:

networks:
  app-network:
